### ISSUE TITLE
Нью офигенен фича

### ISSUE THREAD

**Issue by Karamax** [Karamax/PCS.2#1]
При забитом порте, увеличивать порт на единицу. А то вдруг кто уже заюзал. @Dimidrol112

**Comment by Dimidrol112** [comment]
Забить порт это надо постараться. Можно в `sock.listen(1)` вместо единички поставить больше кол-во клиентов, но это только если подключенные клиенты не будут успевать обрабатываться, а для этого много клиентов должно быть. @Karamax
